"""rename_uq_projects_composite

Revision ID: a48ad14da82b
Revises: 677e300dd994
Create Date: 2026-08-27 13:12:50.379384

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a48ad14da82b"
down_revision: str | Sequence[str] | None = "677e300dd994"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_projects_organization_id"), "projects", type_="unique")
    op.create_unique_constraint(
        op.f("uq_projects_organization_id_name"), "projects", ["organization_id", "name"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_projects_organization_id_name"), "projects", type_="unique")
    op.create_unique_constraint(
        op.f("uq_projects_organization_id"),
        "projects",
        ["organization_id", "name"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
