# [FILE] — app/core/database.py
"""Async SQLAlchemy engine, session factory and FastAPI dependency.

``get_db`` is the project's single gateway to DB sessions: no module
creates a session directly from the factory. The engine is created at
application startup (lifespan) then bound to the factory via
``async_session_factory.configure(bind=engine)``.
"""

# ─── IMPORTS ───
from collections.abc import AsyncGenerator

from sqlalchemy import MetaData
from sqlalchemy.ext.asyncio import (
    AsyncEngine,
    AsyncSession,
    async_sessionmaker,
    create_async_engine,
)
from sqlalchemy.orm import DeclarativeBase

from app.core.config import settings

# ──────────────

# [CODE_START]

NAMING_CONVENTION: dict[str, str] = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Declarative base shared by every SQLAlchemy model of the project.

    Invariant: every constraint (PK, FK, UNIQUE, CHECK, index) receives
    a deterministic name via ``NAMING_CONVENTION`` — the condition for
    reproducible autogenerated migrations (D3), never a name chosen by
    PostgreSQL.
    """

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


async_session_factory: async_sessionmaker[AsyncSession] = async_sessionmaker(
    autoflush=False,
    expire_on_commit=False,
)


# [RAG]
# signature: get_db() -> AsyncGenerator[AsyncSession, None]
# tier: CRITICAL_CORE
# weight: 25
# reads: none
# mutates: none
# calls: none
# called_by: 25 inbound calls — 5 domains (comments, organizations, projects, tasks,
#   users) — details: TOPOLOGY.yaml
# [/RAG]
async def get_db() -> AsyncGenerator[AsyncSession, None]:
    """Provides one DB session per HTTP request (FastAPI dependency).

    Invariants:
    - one HTTP request = one session, closed no matter what on the way
      out;
    - the factory must have been bound to an engine at startup
      (lifespan), otherwise opening a session fails.
    """
    # ─── ZONE DE DÉCLARATION DES VARIABLES ───
    session: AsyncSession
    # ─────────────────────────────────────────

    # [STEP 1] Open a session from the factory → session bound to the current engine
    async with async_session_factory() as session:
        # [STEP 2] Yield the session to the caller → closing guaranteed on context exit
        yield session


# [RAG]
# signature: init_db_engine() -> AsyncEngine
# tier: CORE
# weight: 2
# reads: settings
# mutates: none
# calls: none
# called_by: main.lifespan, scripts.seed.run
# [/RAG]
def init_db_engine() -> AsyncEngine:
    """Creates the project's async engine from the ``settings`` DSN.

    Edge cases:
    - no ping is emitted here: an invalid DSN only fails at the first
      real connection (schema synchronization at startup).
    """
    # ─── ZONE DE DÉCLARATION DES VARIABLES ───
    engine: AsyncEngine
    # ─────────────────────────────────────────

    # [STEP 1] Build the engine from the DSN → engine ready, no connection opened
    engine = create_async_engine(
        settings.database_url,
        echo=settings.sqlalchemy_echo,
        max_overflow=20,
        pool_size=10,
    )
    return engine
